commitLagoona
Mysterio0535/lagoonaHotels pull request #1
Opened 2023-04-16 15:00 UTC by Mysterio0535

2023-04-18 08:43 UTC, BroadenYourMind requested changes

2023-04-18 08:43 UTC, BroadenYourMind commented on index.html
> +                    </a>
Телефон должен быть отдельной ссылкой, а не внутри ссылки с лого. У лого точно правильный путь?

2023-04-18 08:43 UTC, BroadenYourMind commented on index.html
> +                    <div class=""></div>
Это зачем?

2023-04-18 08:43 UTC, BroadenYourMind commented on index.html
> +                    </button>
Я бы кнопку обернул в ссылку, а не наоборот. Почему? Попробуй кликни не на текст в кнопке.

2023-04-18 08:56 UTC, BroadenYourMind commented
<img width="1269" alt="Screenshot 2023-04-18 at 10 43 48" src="https://user-images.githubusercontent.com/102143527/232723242-5c7c809c-aea6-4906-96e6-3f5aca3fb093.png">

- Добавь отступ сверху, контент не должен упираться в потолок.

- Номер телефона подвинь от лого 

<img width="1529" alt="Screenshot 2023-04-18 at 10 45 29" src="https://user-images.githubusercontent.com/102143527/232723743-b1356c2a-b2c8-495f-9c65-ef3adde4c2e7.png">

- сейчас верхний отступ от дочернего компонента <h2 class="do-title">,  а должен быть от родителя, то есть main. Это касательно самого верхнего отспупа. Для всех остальный таких случаев, от section.

2023-04-18 08:58 UTC, BroadenYourMind requested changes

2023-04-18 08:58 UTC, BroadenYourMind commented on index.html
> +                            <div class="services-item">
Зачем тут этот  div  c таким же классом, что и li?

2023-04-18 10:03 UTC, Mysterio0535 commented on index.html
> +                    <div class=""></div>
+

2023-04-18 10:14 UTC, Mysterio0535 commented on index.html
> +                    </a>
+

2023-04-18 10:14 UTC, Mysterio0535 commented on index.html
> +                    </button>
+

2023-04-18 10:17 UTC, Mysterio0535 commented on index.html
> +                            <div class="services-item">
+

2023-04-18 10:25 UTC, Mysterio0535 commented on index.html
> +                    </a>
+

2023-04-19 08:09 UTC, BroadenYourMind commented
<img width="1225" alt="Screenshot 2023-04-19 at 10 08 12" src="https://user-images.githubusercontent.com/102143527/233010942-bdd0b65e-f2f8-4418-914c-6f9274c4c0f4.png">
Повело вёрстку

2023-04-19 08:15 UTC, BroadenYourMind commented
<img width="576" alt="Screenshot 2023-04-19 at 10 12 53" src="https://user-images.githubusercontent.com/102143527/233012223-bf4e9ce9-a4ba-44fa-b138-2f08496efc85.png">
<img width="385" alt="Screenshot 2023-04-19 at 10 17 53" src="https://user-images.githubusercontent.com/102143527/233013247-922f90d1-4095-4804-be5e-0870d41304d5.png">


В таких блоках всегда устанавливай падинг с двух сторон, а то при меньших расширениях экрана будет херово выглядеть

2023-04-29 13:36 UTC, merged